// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PptNemocnice.api.Data;

#nullable disable

namespace PptNemocnice.api.Migrations
{
    [DbContext(typeof(NemocniceDbContext))]
    [Migration("20220509193419_pridani kodu pojistoven")]
    partial class pridanikodupojistoven
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("PptNemocnice.api.Data.Revize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VybaveniId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VybaveniId");

                    b.ToTable("Revizes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01631c28-10e9-4a04-bcd1-91cbececad23"),
                            DateTime = new DateTime(2019, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "AAA",
                            VybaveniId = new Guid("5a3ed44c-ad9a-4b9d-a1ea-b0deabeb815a")
                        },
                        new
                        {
                            Id = new Guid("aa7a1c28-10e9-4a04-bcd1-91cbececad23"),
                            DateTime = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "BBB",
                            VybaveniId = new Guid("5a3ed44c-ad9a-4b9d-a1ea-b0deabeb815a")
                        },
                        new
                        {
                            Id = new Guid("bb0b1c28-10e9-4a04-bcd1-91cbececad23"),
                            DateTime = new DateTime(1999, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CCC",
                            VybaveniId = new Guid("5a3ed44c-ad9a-4b9d-a1ea-b0deabeb815a")
                        },
                        new
                        {
                            Id = new Guid("cc9b1c28-10e9-4a04-bcd1-91cbececad23"),
                            DateTime = new DateTime(2018, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "DDD",
                            VybaveniId = new Guid("b88f888d-b16a-4ffc-9bd5-7f6f5cb607b9")
                        });
                });

            modelBuilder.Entity("PptNemocnice.api.Data.Ukon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VybaveniId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VybaveniId");

                    b.ToTable("Ukons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc771c28-10e9-4a04-bcd1-91cbececad23"),
                            DateTime = new DateTime(2019, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Info = "Aliquam ornare",
                            Kod = "211",
                            Name = "HHH",
                            VybaveniId = new Guid("5a3ed44c-ad9a-4b9d-a1ea-b0deabeb815a")
                        },
                        new
                        {
                            Id = new Guid("dd881c28-10e9-4a04-bcd1-91cbececad23"),
                            DateTime = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Info = "Neque porro",
                            Kod = "111",
                            Name = "ZZZ",
                            VybaveniId = new Guid("5a3ed44c-ad9a-4b9d-a1ea-b0deabeb815a")
                        },
                        new
                        {
                            Id = new Guid("ee991c28-10e9-4a04-bcd1-91cbececad23"),
                            DateTime = new DateTime(2016, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Info = "Duis risus",
                            Kod = "213",
                            Name = "MMM",
                            VybaveniId = new Guid("5a3ed44c-ad9a-4b9d-a1ea-b0deabeb815a")
                        },
                        new
                        {
                            Id = new Guid("ff001c28-10e9-4a04-bcd1-91cbececad23"),
                            DateTime = new DateTime(2022, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Info = "Fusce suscipit",
                            Kod = "201",
                            Name = "III",
                            VybaveniId = new Guid("5a3ed44c-ad9a-4b9d-a1ea-b0deabeb815a")
                        },
                        new
                        {
                            Id = new Guid("ab501c28-10e9-4a04-bcd1-91cbececad23"),
                            DateTime = new DateTime(2016, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Info = "Cras id dolor",
                            Kod = "205",
                            Name = "VVV",
                            VybaveniId = new Guid("b88f888d-b16a-4ffc-9bd5-7f6f5cb607b9")
                        },
                        new
                        {
                            Id = new Guid("cb661c28-10e9-4a04-bcd1-91cbececad23"),
                            DateTime = new DateTime(2016, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Info = "Mauris dictum",
                            Kod = "209",
                            Name = "OOO",
                            VybaveniId = new Guid("b88f888d-b16a-4ffc-9bd5-7f6f5cb607b9")
                        });
                });

            modelBuilder.Entity("PptNemocnice.api.Data.Vybaveni", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BoughtDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vybavenis");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a3ed44c-ad9a-4b9d-a1ea-b0deabeb815a"),
                            BoughtDate = new DateTime(2018, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "XXX",
                            Price = 555
                        },
                        new
                        {
                            Id = new Guid("b88f888d-b16a-4ffc-9bd5-7f6f5cb607b9"),
                            BoughtDate = new DateTime(2000, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "AZU",
                            Price = 10888
                        },
                        new
                        {
                            Id = new Guid("39d4018a-ba22-4ab6-b582-0d1c35e79e45"),
                            BoughtDate = new DateTime(2020, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "JQW",
                            Price = 999
                        });
                });

            modelBuilder.Entity("PptNemocnice.api.Data.Revize", b =>
                {
                    b.HasOne("PptNemocnice.api.Data.Vybaveni", "Vybaveni")
                        .WithMany("Revizes")
                        .HasForeignKey("VybaveniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vybaveni");
                });

            modelBuilder.Entity("PptNemocnice.api.Data.Ukon", b =>
                {
                    b.HasOne("PptNemocnice.api.Data.Vybaveni", "Vybaveni")
                        .WithMany("Ukons")
                        .HasForeignKey("VybaveniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vybaveni");
                });

            modelBuilder.Entity("PptNemocnice.api.Data.Vybaveni", b =>
                {
                    b.Navigation("Revizes");

                    b.Navigation("Ukons");
                });
#pragma warning restore 612, 618
        }
    }
}
